# -*- coding: utf-8 -*-
"""Twitter_Demograaphic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VcL87Hr6u72h2_3E1hX_axbCSZvmVxnf

The below code installs the necessary libary to predict the age of Twitter Users
"""

pip install m3inference

"""The below code sets up the M3 app and logs us into twitter using our unique private keys"""

import pprint
from m3inference import M3Twitter
m3twitter=M3Twitter()

# initialize twitter api
m3twitter.twitter_init(api_key="",api_secret="",access_token="",access_secret="")

"""Below is the function to search a screen name directly from twitter and return the results prediction which is stored in a dictionary string"""

name = "720629000000000000" 
pprint.pprint(m3twitter.infer_id(name))

data = m3twitter.infer_screen_name(name)

print(data)

UserID = data['input']['id']
ScreenName = data['input']['screen_name']
Male_Prediction = data['output']['gender']['male']
Female_Prediction = data['output']['gender']['female']
AgeLess18 = data['output']['age']['<=18']
Age19_29 = data['output']['age']['19-29']
Age30_39 = data['output']['age']['30-39']
AgeOver40 = data['output']['age']['>=40']
NonOrg = data['output']['org']['non-org']
IsOrg = data['output']['org']['is-org']

import pandas as pd  
  
# assign data of lists.  
data2 = {'User_id': [UserID],'Screen_Name' : [ScreenName] ,'Male_Pre': [Male_Prediction],'Female_Pre' :[Female_Prediction],'AgeLess18' : [AgeLess18],'Age19_29' :[Age19_29], 'Age30_39' : [Age30_39] ,'AgeOver40':[AgeOver40],'NonOrg': NonOrg, 'IsOrg':IsOrg }  
  
# Create DataFrame  
df = pd.DataFrame(data2)  
  
# Print the output.  
print(df)

"""Here we will add the code that will allow us to add another row to our dataframe."""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import io

df2 = pd.read_csv(io.StringIO(uploaded['Unique_ids.csv'].decode('utf-8')))

#df2 = df2.applymap(int)

Name_list = df2["Unique_ids"].tolist()
SubsetList = Name_list[0:20]
print(SubsetList)

for id2 in SubsetList:
 JsonM3= m3twitter.infer_id(id2)
 if JsonM3 != None :
   UserID = JsonM3['input']['id']
   ScreenName = JsonM3['input']['screen_name']
   Male_Prediction = JsonM3['output']['gender']['male']
   Female_Prediction = JsonM3['output']['gender']['female']
   AgeLess18 = JsonM3['output']['age']['<=18']
   Age19_29 = JsonM3['output']['age']['19-29']
   Age30_39 = JsonM3['output']['age']['30-39']
   AgeOver40 = JsonM3['output']['age']['>=40']
   NonOrg = JsonM3['output']['org']['non-org']
   IsOrg = JsonM3['output']['org']['is-org']
   new_row = {'User_id': UserID,'Screen_Name' : ScreenName ,'Male_Pre': Male_Prediction,'Female_Pre' :Female_Prediction,'AgeLess18' : AgeLess18,'Age19_29' :Age19_29, 'Age30_39' : Age30_39 ,'AgeOver40':AgeOver40,'NonOrg': NonOrg, 'IsOrg':IsOrg }
   df = df.append(new_row, ignore_index=True)

print(df)
